name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 52.66.166.251 # <-- Replace with your actual public IP
          username: bitnami
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/bitnami/apache/htdocs
            git pull origin main
